name: test input var pass b/w steps             
on: 
  workflow_dispatch:
    inputs:
            
      App_Deploy_Env:
        description: "Please Choose App Env to Deploy"
        type: choice
        options:
        - "stage"
        - "mo"
        - "portal_prod-1-4"
        - "portal_prod-5-9"
        - "portal_prod-10-15"
        - "callcenter_prod-1-2"                     
        - "callcenter_prod-3-4"      
        - "callcenter_prod-5-6"  
        - "apibatch_prod-1-2" 
        - "apibatch_prod-3-4"
        - "batch_prod-1-3" 
        - "batch_prod-5-18"         
        required: true
        default: " "   
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: ${{ inputs.App_Deploy_Env}}
    steps:
      - name: passinput
        id: vars
        run: |
           i1="${{ inputs.App_Deploy_Env }}"
           code1=$(echo $i1 |cut -f1 -d_)           
           echo $code1
           echo "code1=$code1 ">> $GITHUB_OUTPUT
      - name: passinput1
        run: |
           echo "p1"   
           
           echo "${{ steps.vars.outputs.code1 }}"
